# -*- coding: utf-8 -*-
"""C_Clientes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oc0qiHui1Am8LHnhaTpg-ozPXewgDdQ4
"""

https://raw.githubusercontent.com/BryanJimenezUtec/etl-data-pipeline2520552022/refs/heads/main/data/raw/C_clientes.csv

import pandas as pd

url ="https://raw.githubusercontent.com/BryanJimenezUtec/etl-data-pipeline2520552022/refs/heads/main/data/raw/C_clientes.csv"
df = pd.read_csv(url)
df.head()

#Exploración de datos
df.shape
df.columns
df.info()
df.isnull().sum()

"""LIMPIEZA DE DATOS"""

# 1. Copia y normalización de nombres de columnas
clientes_new = df.copy()
clientes_new.columns = clientes_new.columns.str.strip().str.lower()

# 2. Limpieza de Texto
clientes_new['cliente'] = clientes_new['cliente'].astype(str).str.strip().str.title()
clientes_new['ciudad'] = clientes_new['ciudad'].astype(str).str.strip().str.title()

# 3. Eliminar duplicados
clientes_new = clientes_new.drop_duplicates()

# 4. Estandarización de Nulos
clientes_new = clientes_new.replace(r'^\s*$', pd.NA, regex=True)

# Expresión regular para validar correos electrónicos
regex_correo = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'

# Creamos una columna temporal para marcar correos válidos
clientes_new['correo_valido'] = clientes_new['correo'].str.match(regex_correo, na=False)

import re
regex_correo = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'

# 2. Crear una máscara de validación de correo
correo_formato_valido = clientes_new['correo'].str.match(regex_correo, na=False)

# 3. Separar datos válidos
validos_cl = clientes_new[
    clientes_new['id_cliente'].notna() &
    clientes_new['cliente'].notna() &
    (correo_formato_valido == True)
].copy()

# 4. Separar datos rechazados

rechazados_cl = clientes_new[
    clientes_new['id_cliente'].isna() |
    clientes_new['cliente'].isna() |
    (correo_formato_valido == False)
].copy()

# Verificar los resultados
print(f"Clientes con datos perfectos: {len(validos_cl)}")
print(f"Clientes rechazados (por nulos o correo inválido): {len(rechazados_cl)}")

#Motivo de Rechazo
regex_correo = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'

def motivo_cliente(row):
    motivos = []


    if pd.isna(row['id_cliente']):
        motivos.append("id_vacio")


    if pd.isna(row['cliente']) or str(row['cliente']).lower() == 'nan':
        motivos.append("nombre_vacio")

    if pd.isna(row['correo']) or str(row['correo']).lower() == 'nan':
        motivos.append("correo_vacio")
    elif not re.match(regex_correo, str(row['correo'])):
        motivos.append("formato_correo_invalido")

    return ",".join(motivos)

rechazados_cl["motivo_rechazo"] = rechazados_cl.apply(motivo_cliente, axis=1)

# Exportar archivos procesados de Nuevos Clientes
validos_cl.to_csv("c_clientes_curated.csv", index=False)
rechazados_cl.to_csv("c_clientes_rejects.csv", index=False)

print("Archivos 'c_clientes_curated.csv' y 'c_clientes_rejects.csv' generados con éxito.")

"""Conectar BD a render"""

!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_user:KWIr9XJ0F6G6c8YE7pj9J9RzFgRA6wo5@dpg-d6qu5nlm5p6s73ea88hg-a.oregon-postgres.render.com/etl_seguros_ibd2"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

# 1. Asegúrate de que validos_cl solo tenga las columnas que quieres
# Quitamos 'correo_valido' para que no ensucie la base de datos
columnas_a_guardar = ['id_cliente', 'cliente', 'correo', 'ciudad']
validos_cl_final = validos_cl[columnas_a_guardar]

# 2. Usamos 'replace' para que la tabla en Render ahora tenga estos nombres
validos_cl_final.to_sql(
    'clientes_curated',
    engine,
    if_exists='replace',
    index=False
)

# 3. Hacemos lo mismo con los rechazados para que sean consistentes
rechazados_cl.to_sql(
    'clientes_rejects',
    engine,
    if_exists='replace',
    index=False
)

print("Tabla actualizada. Ahora los nombres son 'cliente', 'correo' y se incluyó 'ciudad'.")

# Validar los primeros 10 registros con la nueva estructura
pd.read_sql("SELECT * FROM clientes_curated LIMIT 10", engine)

# Validar el conteo de clientes por ciudad
query_ciudades = """
SELECT
    ciudad,
    COUNT(id_cliente) as total_clientes
FROM clientes_curated
GROUP BY ciudad
ORDER BY total_clientes DESC
"""

pd.read_sql(query_ciudades, engine)