# -*- coding: utf-8 -*-
"""Pagos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16kgDk5GBKqjbI0d2EQXgKo4gV_hefqYc
"""

https://raw.githubusercontent.com/BryanJimenezUtec/etl-data-pipeline2520552022/refs/heads/main/data/raw/C_pagos.csv

import pandas as pd

url ="https://raw.githubusercontent.com/BryanJimenezUtec/etl-data-pipeline2520552022/refs/heads/main/data/raw/C_pagos.csv"
df = pd.read_csv(url)
df.head()

#Exploración de datos
df.shape
df.columns
df.info()
df.isnull().sum()

"""LIMPIEZA DE DATOS"""

pagos = df.copy()
pagos.columns = pagos.columns.str.strip().str.lower()

pagos['monto_pagado'] = pagos['monto_pagado'].astype(str).str.strip()

pagos['monto_pagado'] = pagos['monto_pagado'].str.replace('$', '', regex=False)
pagos['monto_pagado'] = pagos['monto_pagado'].str.replace('USD', '', regex=False)
pagos['monto_pagado'] = pagos['monto_pagado'].str.replace(',', '', regex=False).str.strip()

# Convertir a valor numérico
pagos['monto_pagado'] = pd.to_numeric(pagos['monto_pagado'], errors='coerce')

# 3. Ajuste adicional
pagos['metodo'] = pagos['metodo'].astype(str).str.strip().str.title()

# 4. Estandarización de nulos
pagos = pagos.replace(r'^\s*$', pd.NA, regex=True)

# Separar datos válidos y rechazados para Pagos
validos_pg = pagos[
    pagos['id_pago'].notna() &
    pagos['id_venta'].notna() &
    pagos['monto_pagado'].notna()
].copy()

rechazados_pg = pagos[
    pagos['id_pago'].isna() |
    pagos['id_venta'].isna() |
    pagos['monto_pagado'].isna()
].copy()

print(f"Pagos procesados correctamente: {len(validos_pg)}")
print(f"Pagos con errores de formato o nulos: {len(rechazados_pg)}")

# Motivo de rechazo
def motivo_pago(row):
    motivos = []

    if pd.isna(row['id_pago']):
        motivos.append("id_pago_vacio")

    if pd.isna(row['id_venta']):
        motivos.append("id_venta_vacio")

    # Validar Monto
    if pd.isna(row['monto_pagado']):
        motivos.append("monto_nulo_o_formato_invalido")

    return ",".join(motivos)

# 2. Aplicar la función al DataFrame de rechazados
rechazados_pg["motivo_rechazo"] = rechazados_pg.apply(motivo_pago, axis=1)

# 3. Ver los primeros resultados de rechazados
print("Muestra de registros rechazados y sus motivos:")
print(rechazados_pg[['id_pago', 'monto_pagado', 'motivo_rechazo']].head())

# Exportar archivos procesados de Pagos
validos_pg.to_csv("c_pagos_curated.csv", index=False)
rechazados_pg.to_csv("c_pagos_rejects.csv", index=False)

print("Archivos 'c_pagos_curated.csv' y 'c_pagos_rejects.csv' generados con éxito.")

"""Conectar BD a render"""

!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_user:KWIr9XJ0F6G6c8YE7pj9J9RzFgRA6wo5@dpg-d6qu5nlm5p6s73ea88hg-a.oregon-postgres.render.com/etl_seguros_ibd2"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

# 1. Cargar pagos válidos a PostgreSQL

validos_pg.to_sql(
    'pagos_curated',
    engine,
    if_exists='replace',
    index=False
)

# 2. Cargar registros rechazados
rechazados_pg.to_sql(
    'pagos_rejects',
    engine,
    if_exists='replace',
    index=False
)

print(f"Carga finalizada: {len(validos_pg)} pagos registrados en la base de datos.")

# Validar los primeros 10 registros de la tabla de pagos
pd.read_sql("SELECT * FROM pagos_curated LIMIT 10", engine)