# -*- coding: utf-8 -*-
"""Ventas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xqaNga8K2GsbaBwNBEGE5dd2H6lRdEXz
"""

https://raw.githubusercontent.com/BryanJimenezUtec/etl-data-pipeline2520552022/refs/heads/main/data/raw/C_ventas.csv

import pandas as pd

url ="https://raw.githubusercontent.com/BryanJimenezUtec/etl-data-pipeline2520552022/refs/heads/main/data/raw/C_ventas.csv"
df = pd.read_csv(url)
df.head()

#Exploración de datos
df.shape
df.columns
df.info()
df.isnull().sum()

"""LIMPIEZA DE DATOS"""

ventas = df.copy()
ventas.columns = ventas.columns.str.strip().str.lower()

ventas['total'] = ventas['total'].astype(str).str.replace('$', '', regex=False)
ventas['total'] = ventas['total'].str.replace('USD', '', regex=False)
ventas['total'] = ventas['total'].str.replace(',', '', regex=False).str.strip()

# Convertimos a tipo numérico decimal
ventas['total'] = pd.to_numeric(ventas['total'], errors='coerce')

#  Limpieza de columna 'fecha'
ventas['fecha'] = pd.to_datetime(ventas['fecha'], errors='coerce')

#  Limpieza de IDs
ventas['id_venta'] = ventas['id_venta'].astype(str).str.strip().str.upper()
ventas['id_cliente'] = ventas['id_cliente'].astype(str).str.strip().str.upper()

#  Estandarización de nulos
ventas = ventas.replace(r'^\s*$', pd.NA, regex=True)

# Separar datos válidos y rechazados para Ventas

validos_vn = ventas[
    ventas['id_venta'].notna() &
    ventas['id_cliente'].notna() &
    ventas['fecha'].notna() &
    ventas['total'].notna()
].copy()

rechazados_vn = ventas[
    ventas['id_venta'].isna() |
    ventas['id_cliente'].isna() |
    ventas['fecha'].isna() |
    ventas['total'].isna()
].copy()

# Verificar los resultados en la consola
print(f"Ventas procesadas correctamente: {len(validos_vn)}")
print(f"Ventas con errores (fecha, total o nulos): {len(rechazados_vn)}")

def motivo_venta(row):
    motivos = []

    # Validar ID de Venta
    if pd.isna(row['id_venta']) or str(row['id_venta']).lower() == 'nan':
        motivos.append("id_venta_vacio")

    # Validar ID de Cliente
    if pd.isna(row['id_cliente']) or str(row['id_cliente']).lower() == 'nan':
        motivos.append("id_cliente_vacio")

    # Validar Fecha (NaT ocurre si estaba vacía o el formato era erróneo)
    if pd.isna(row['fecha']):
        motivos.append("fecha_invalida_o_vacia")

    # Validar Total (NaN si no se pudo convertir a decimal tras quitar $ o USD)
    if pd.isna(row['total']):
        motivos.append("total_nulo_o_formato_error")

    return ",".join(motivos)

rechazados_vn["motivo_rechazo"] = rechazados_vn.apply(motivo_venta, axis=1)

#  Ver los primeros resultados de rechazados
print("Muestra de ventas rechazadas y sus motivos:")
print(rechazados_vn[['id_venta', 'total', 'motivo_rechazo']].head())

# Exportar archivos procesados de Ventas
validos_vn.to_csv("c_ventas_curated.csv", index=False)
rechazados_vn.to_csv("c_ventas_rejects.csv", index=False)

print("Archivos 'c_ventas_curated.csv' y 'c_ventas_rejects.csv' generados con éxito.")

"""Conectar BD a render"""

!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_user:KWIr9XJ0F6G6c8YE7pj9J9RzFgRA6wo5@dpg-d6qu5nlm5p6s73ea88hg-a.oregon-postgres.render.com/etl_seguros_ibd2"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

# Cargar ventas válidas a PostgreSQL

validos_vn.to_sql(
    'ventas_curated',
    engine,
    if_exists='replace',
    index=False
)

#  Cargar registros rechazados de ventas
rechazados_vn.to_sql(
    'ventas_rejects',
    engine,
    if_exists='replace',
    index=False
)

print(f"Carga finalizada: {len(validos_vn)} ventas registradas en la base de datos.")

# Validar los primeros 10 registros de la tabla de ventas
pd.read_sql("SELECT * FROM ventas_curated LIMIT 10", engine)